server:
  port: 8080

spring:
  application:
    name: eureka-provider
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8888/eureka

