server:
  port: 8081

spring:
  application:
    name: consumer-ribbon

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8888/eureka
